/* prjParams.h - dynamically generated configuration header */


/*
GENERATED: Wed Apr 28 16:45:33 Pacific Daylight Time 1999
DO NOT EDIT - file is regenerated whenever the project changes
*/

#ifndef INCprjParamsh
#define INCprjParamsh


/*** INCLUDED COMPONENTS ***/

#define INCLUDE_ANSI_ASSERT
#define INCLUDE_ANSI_CTYPE
#define INCLUDE_ANSI_LOCALE
#define INCLUDE_ANSI_MATH
#define INCLUDE_ANSI_STDIO
#define INCLUDE_ANSI_STDIO_EXTRA
#define INCLUDE_ANSI_STDLIB
#define INCLUDE_ANSI_STRING
#define INCLUDE_ANSI_TIME
#define INCLUDE_BUF_MGR
#define INCLUDE_CACHE_ENABLE
#define INCLUDE_CACHE_SUPPORT
#define INCLUDE_CPLUS
#define INCLUDE_CPLUS_IOSTREAMS
#define INCLUDE_CPLUS_STL
#define INCLUDE_DLL
#define INCLUDE_ENV_VARS
#define INCLUDE_EXC_HANDLING
#define INCLUDE_EXC_TASK
#define INCLUDE_FLOATING_POINT
#define INCLUDE_FORMATTED_IO
#define INCLUDE_HASH
#define INCLUDE_IO_SYSTEM
#define INCLUDE_KERNEL
#define INCLUDE_LOGGING
#define INCLUDE_MEMORY_CONFIG
#define INCLUDE_MEM_MGR_BASIC
#define INCLUDE_MEM_MGR_FULL
#define INCLUDE_MODULE_MANAGER
#define INCLUDE_MSG_Q
#define INCLUDE_MSG_Q_SHOW
#define INCLUDE_NTPASSFS
#define INCLUDE_PIPES
#define INCLUDE_POSIX_CLOCKS
#define INCLUDE_RBUFF
#define INCLUDE_RNG_BUF
#define INCLUDE_SELECT
#define INCLUDE_SEM_BINARY
#define INCLUDE_SEM_COUNTING
#define INCLUDE_SEM_MUTEX
#define INCLUDE_SEQ_TIMESTAMP
#define INCLUDE_SIGNALS
#define INCLUDE_SIO
#define INCLUDE_STDIO
#define INCLUDE_SYM_TBL
#define INCLUDE_SYSCLK_INIT
#define INCLUDE_SYSHW_INIT
#define INCLUDE_SYS_START
#define INCLUDE_TASK_HOOKS
#define INCLUDE_TASK_SHOW
#define INCLUDE_TASK_VARS
#define INCLUDE_TIMEX
#define INCLUDE_TRIGGERING
#define INCLUDE_TTY_DEV
#define INCLUDE_USER_APPL
#define INCLUDE_WATCHDOGS
#define INCLUDE_WDB
#define INCLUDE_WDB_BANNER
#define INCLUDE_WDB_BP
#define INCLUDE_WDB_COMM_PIPE
#define INCLUDE_WDB_CTXT
#define INCLUDE_WDB_DIRECT_CALL
#define INCLUDE_WDB_EVENTPOINTS
#define INCLUDE_WDB_EVENTS
#define INCLUDE_WDB_EXC_NOTIFY
#define INCLUDE_WDB_EXIT_NOTIFY
#define INCLUDE_WDB_FUNC_CALL
#define INCLUDE_WDB_GOPHER
#define INCLUDE_WDB_MEM
#define INCLUDE_WDB_REG
#define INCLUDE_WDB_START_NOTIFY
#define INCLUDE_WDB_SYS
#define INCLUDE_WDB_TASK
#define INCLUDE_WDB_TASK_BP
#define INCLUDE_WDB_TSFS
#define INCLUDE_WDB_USER_EVENT
#define INCLUDE_WDB_VIO
#define INCLUDE_WDB_VIO_LIB
#define INCLUDE_WINDVIEW
#define INCLUDE_WINDVIEW_CLASS
#define INCLUDE_WVUPLOAD_FILE
#define INCLUDE_WVUPLOAD_TSFSSOCK
#undef INCLUDE_PROTECT_TEXT
#undef INCLUDE_PROTECT_VEC_TABLE
#undef INCLUDE_PCI_PARAMS
#undef INCLUDE_VME_PARAMS
#undef INCLUDE_PCMCIA
#undef INCLUDE_SCSI
#undef INCLUDE_LPT
#undef INCLUDE_FD
#undef INCLUDE_TFFS
#undef INCLUDE_IDE
#undef INCLUDE_ATA
#undef INCLUDE_AUX_CLK
#undef INCLUDE_TIMESTAMP
#undef INCLUDE_PC_CONSOLE
#undef INCLUDE_MMU_FULL
#undef INCLUDE_MMU_BASIC
#undef INCLUDE_DOSFS
#undef INCLUDE_TYCODRV_5_2
#undef INCLUDE_SW_FP
#undef INCLUDE_HW_FP
#undef INCLUDE_LOOPBACK
#undef INCLUDE_DC
#undef INCLUDE_EGL
#undef INCLUDE_EI
#undef INCLUDE_FEI
#undef INCLUDE_EX
#undef INCLUDE_ENP
#undef INCLUDE_IE
#undef INCLUDE_ILAC
#undef INCLUDE_LN
#undef INCLUDE_LNSGI
#undef INCLUDE_NIC
#undef INCLUDE_NIC_EVB
#undef INCLUDE_MED
#undef INCLUDE_ELC
#undef INCLUDE_ULTRA
#undef INCLUDE_EEX
#undef INCLUDE_ELT
#undef INCLUDE_QU
#undef INCLUDE_ENE
#undef INCLUDE_ESMC
#undef INCLUDE_SN
#undef INCLUDE_OLI
#undef INCLUDE_USR_ENTRIES
#undef INCLUDE_IF_USR
#undef INCLUDE_LNEBSA
#undef INCLUDE_FN
#undef INCLUDE_BSD
#undef INCLUDE_MUX
#undef INCLUDE_NET_SETUP
#undef INCLUDE_NETWORK
#undef INCLUDE_NETMASK_GET
#undef INCLUDE_NETDEV_NAMEGET
#undef INCLUDE_RPC
#undef INCLUDE_ZBUF_SOCK
#undef INCLUDE_BSD_BOOT
#undef INCLUDE_END
#undef INCLUDE_END_BOOT
#undef INCLUDE_PPP
#undef INCLUDE_PPP_BOOT
#undef INCLUDE_PPP_CRYPT
#undef INCLUDE_SLIP
#undef INCLUDE_SLIP_BOOT
#undef INCLUDE_OSPF
#undef INCLUDE_RIP
#undef INCLUDE_ROUTE_SOCK
#undef INCLUDE_DNS_RESOLVER
#undef INCLUDE_DHCPC
#undef INCLUDE_DHCPR
#undef INCLUDE_DHCPS
#undef INCLUDE_SNTPC
#undef INCLUDE_SNTPS
#undef INCLUDE_BOOTP
#undef INCLUDE_PING
#undef INCLUDE_TELNET
#undef INCLUDE_RLOGIN
#undef INCLUDE_SECURITY
#undef INCLUDE_HTTP
#undef INCLUDE_FTP_SERVER
#undef INCLUDE_FTPD_SECURITY
#undef INCLUDE_NFS
#undef INCLUDE_NFS_MOUNT_ALL
#undef INCLUDE_NFS_SERVER
#undef INCLUDE_TFTP_CLIENT
#undef INCLUDE_TFTP_SERVER
#undef INCLUDE_IP
#undef INCLUDE_TCP
#undef INCLUDE_TCP_DEBUG
#undef INCLUDE_UDP
#undef INCLUDE_IP_FILTER
#undef INCLUDE_ICMP
#undef INCLUDE_IGMP
#undef INCLUDE_NET_LIB
#undef INCLUDE_BSD_SOCKET
#undef BSD43_COMPATIBLE
#undef INCLUDE_MCAST_ROUTING
#undef INCLUDE_ARP_API
#undef INCLUDE_HOST_TBL
#undef INCLUDE_STREAMS
#undef INCLUDE_STREAMS_ALL
#undef INCLUDE_STREAMS_AUTOPUSH
#undef INCLUDE_STREAMS_DEBUG
#undef INCLUDE_STREAMS_DLPI
#undef INCLUDE_STREAMS_SOCKET
#undef INCLUDE_STREAMS_STRACE
#undef INCLUDE_STREAMS_STRERR
#undef INCLUDE_STREAMS_TLI
#undef INCLUDE_PROXY_CLIENT
#undef INCLUDE_PROXY_DEFAULT_ADDR
#undef INCLUDE_PROXY_SERVER
#undef INCLUDE_SM_NET_ADDRGET
#undef INCLUDE_SECOND_SMNET
#undef INCLUDE_SM_NET
#undef INCLUDE_SM_SEQ_ADDR
#undef INCLUDE_MIB2_ALL
#undef INCLUDE_MIB2_AT
#undef INCLUDE_MIB2_ICMP
#undef INCLUDE_MIB2_IF
#undef INCLUDE_MIB2_IP
#undef INCLUDE_MIB2_SYSTEM
#undef INCLUDE_MIB2_TCP
#undef INCLUDE_MIB2_UDP
#undef INCLUDE_SNMPD
#undef INCLUDE_DHCPC_SHOW
#undef INCLUDE_UDP_SHOW
#undef INCLUDE_TCP_SHOW
#undef INCLUDE_ICMP_SHOW
#undef INCLUDE_IGMP_SHOW
#undef INCLUDE_NET_SHOW
#undef INCLUDE_SM_NET_SHOW
#undef INCLUDE_DHCPC_LEASE_TEST
#undef INCLUDE_NET_INIT
#undef INCLUDE_DEFER_NET_INIT
#undef INCLUDE_BOOT_LINE_INIT
#undef INCLUDE_DHCPC_LEASE_GET
#undef INCLUDE_DHCPC_LEASE_CLEAN
#undef INCLUDE_NET_HOST_SETUP
#undef INCLUDE_NET_REM_IO
#undef INCLUDE_CPLUS_STRING
#undef INCLUDE_CPLUS_COMPLEX
#undef INCLUDE_CPLUS_IOSTREAMS_FULL
#undef INCLUDE_CPLUS_STRING_IO
#undef INCLUDE_CPLUS_COMPLEX_IO
#undef INCLUDE_CPLUS_IOSTREAMS_TEST
#undef INCLUDE_CPLUS_VXW
#undef INCLUDE_CPLUS_TOOLS
#undef INCLUDE_POSIX_AIO
#undef INCLUDE_POSIX_AIO_SYSDRV
#undef INCLUDE_POSIX_FTRUNC
#undef INCLUDE_POSIX_MEM
#undef INCLUDE_POSIX_MQ
#undef INCLUDE_POSIX_SCHED
#undef INCLUDE_POSIX_SEM
#undef INCLUDE_POSIX_SIGNALS
#undef INCLUDE_POSIX_TIMERS
#undef INCLUDE_CLASS_SHOW
#undef INCLUDE_MEM_SHOW
#undef INCLUDE_MMU_FULL_SHOW
#undef INCLUDE_POSIX_AIO_SHOW
#undef INCLUDE_POSIX_MQ_SHOW
#undef INCLUDE_POSIX_SEM_SHOW
#undef INCLUDE_SEM_SHOW
#undef INCLUDE_STDIO_SHOW
#undef INCLUDE_SYM_TBL_SHOW
#undef INCLUDE_TASK_HOOKS_SHOW
#undef INCLUDE_WATCHDOGS_SHOW
#undef INCLUDE_TRIGGER_SHOW
#undef INCLUDE_RBUFF_SHOW
#undef INCLUDE_ATA_SHOW
#undef INCLUDE_HW_FP_SHOW
#undef INCLUDE_SPY
#undef INCLUDE_CODETEST
#undef INCLUDE_DEBUG
#undef INCLUDE_SHELL_BANNER
#undef INCLUDE_STARTUP_SCRIPT
#undef INCLUDE_SHELL
#undef INCLUDE_STAT_SYM_TBL
#undef INCLUDE_SYM_TBL_SYNC
#undef INCLUDE_CPLUS_DEMANGLER
#undef INCLUDE_SYM_TBL_INIT
#undef INCLUDE_STANDALONE_SYM_TBL
#undef INCLUDE_NET_SYM_TBL
#undef INCLUDE_LOADER
#undef INCLUDE_UNLOADER
#undef INCLUDE_WDB_HW_FP
#undef INCLUDE_WDB_TASK_HW_FP
#undef INCLUDE_WDB_SYS_HW_FP
#undef INCLUDE_WDB_COMM_SERIAL
#undef INCLUDE_WDB_COMM_TYCODRV_5_2
#undef INCLUDE_WDB_COMM_NETWORK
#undef INCLUDE_WDB_COMM_NETROM
#undef INCLUDE_WDB_COMM_END
#undef INCLUDE_WDB_COMM_CUSTOM
#undef INCLUDE_SM_OBJ
#undef INCLUDE_RT11FS
#undef INCLUDE_RAWFS
#undef INCLUDE_RAMDRV
#undef INCLUDE_WVUPLOAD_SOCK
#undef INCLUDE_SYS_TIMESTAMP
#undef INCLUDE_USER_TIMESTAMP
#undef INCLUDE_WV_BUFF_USER
#undef INCLUDE_UGL
#undef UGL_SERIAL_SERVICES
#undef UGL_CONFIG_INPUT_DEVICES
#undef UGL_CONFIG_MALLOC_DEFAULTS
#undef UGL_CONFIG_MALLOC_USER
#undef UGL_CONFIG_CL5434
#undef UGL_CONFIG_CT65550
#undef UGL_CONFIG_CT65555
#undef UGL_CONFIG_CT69000
#undef UGL_CONFIG_CX5530
#undef UGL_CONFIG_IGS5050
#undef UGL_CONFIG_M68328
#undef UGL_CONFIG_M821
#undef UGL_CONFIG_M823
#undef UGL_CONFIG_SA1100D
#undef UGL_CONFIG_VGA
#undef UGL_CONFIG_K8255
#undef UGL_CONFIG_P8250MS
#undef UGL_CONFIG_PPS2MS
#undef UGL_CONFIG_SA1100KB
#undef UGL_CONFIG_SA1100TS
#undef INCLUDE_UGL_FT_BASIC
#undef INCLUDE_UGL_FT_TIMES_08
#undef INCLUDE_UGL_FT_TIMES_10
#undef INCLUDE_UGL_FT_TIMES_12
#undef INCLUDE_UGL_FT_TIMES_14
#undef INCLUDE_UGL_FT_TIMES_18
#undef INCLUDE_UGL_FT_TIMES_24
#undef INCLUDE_UGL_FT_TIMES_I_08
#undef INCLUDE_UGL_FT_TIMES_I_10
#undef INCLUDE_UGL_FT_TIMES_I_12
#undef INCLUDE_UGL_FT_TIMES_I_14
#undef INCLUDE_UGL_FT_TIMES_I_18
#undef INCLUDE_UGL_FT_TIMES_I_24
#undef INCLUDE_UGL_FT_TIMES_B_08
#undef INCLUDE_UGL_FT_TIMES_B_10
#undef INCLUDE_UGL_FT_TIMES_B_12
#undef INCLUDE_UGL_FT_TIMES_B_14
#undef INCLUDE_UGL_FT_TIMES_B_18
#undef INCLUDE_UGL_FT_TIMES_B_24
#undef INCLUDE_UGL_FT_TIMES_BI_08
#undef INCLUDE_UGL_FT_TIMES_BI_10
#undef INCLUDE_UGL_FT_TIMES_BI_12
#undef INCLUDE_UGL_FT_TIMES_BI_14
#undef INCLUDE_UGL_FT_TIMES_BI_18
#undef INCLUDE_UGL_FT_TIMES_BI_24
#undef INCLUDE_UGL_FT_COURIER_08
#undef INCLUDE_UGL_FT_COURIER_10
#undef INCLUDE_UGL_FT_COURIER_12
#undef INCLUDE_UGL_FT_COURIER_14
#undef INCLUDE_UGL_FT_COURIER_18
#undef INCLUDE_UGL_FT_COURIER_24
#undef INCLUDE_UGL_FT_COURIER_I_08
#undef INCLUDE_UGL_FT_COURIER_I_10
#undef INCLUDE_UGL_FT_COURIER_I_12
#undef INCLUDE_UGL_FT_COURIER_I_14
#undef INCLUDE_UGL_FT_COURIER_I_18
#undef INCLUDE_UGL_FT_COURIER_I_24
#undef INCLUDE_UGL_FT_COURIER_B_08
#undef INCLUDE_UGL_FT_COURIER_B_10
#undef INCLUDE_UGL_FT_COURIER_B_12
#undef INCLUDE_UGL_FT_COURIER_B_14
#undef INCLUDE_UGL_FT_COURIER_B_18
#undef INCLUDE_UGL_FT_COURIER_B_24
#undef INCLUDE_UGL_FT_COURIER_BI_08
#undef INCLUDE_UGL_FT_COURIER_BI_10
#undef INCLUDE_UGL_FT_COURIER_BI_12
#undef INCLUDE_UGL_FT_COURIER_BI_14
#undef INCLUDE_UGL_FT_COURIER_BI_18
#undef INCLUDE_UGL_FT_COURIER_BI_24
#undef INCLUDE_UGL_FT_HELV_08
#undef INCLUDE_UGL_FT_HELV_10
#undef INCLUDE_UGL_FT_HELV_12
#undef INCLUDE_UGL_FT_HELV_14
#undef INCLUDE_UGL_FT_HELV_18
#undef INCLUDE_UGL_FT_HELV_24
#undef INCLUDE_UGL_FT_HELV_I_08
#undef INCLUDE_UGL_FT_HELV_I_10
#undef INCLUDE_UGL_FT_HELV_I_12
#undef INCLUDE_UGL_FT_HELV_I_14
#undef INCLUDE_UGL_FT_HELV_I_18
#undef INCLUDE_UGL_FT_HELV_I_24
#undef INCLUDE_UGL_FT_HELV_B_08
#undef INCLUDE_UGL_FT_HELV_B_10
#undef INCLUDE_UGL_FT_HELV_B_12
#undef INCLUDE_UGL_FT_HELV_B_14
#undef INCLUDE_UGL_FT_HELV_B_18
#undef INCLUDE_UGL_FT_HELV_B_24
#undef INCLUDE_UGL_FT_HELV_BI_08
#undef INCLUDE_UGL_FT_HELV_BI_10
#undef INCLUDE_UGL_FT_HELV_BI_12
#undef INCLUDE_UGL_FT_HELV_BI_14
#undef INCLUDE_UGL_FT_HELV_BI_18
#undef INCLUDE_UGL_FT_HELV_BI_24
#undef INCLUDE_UGL_FT_LUCIDA_08
#undef INCLUDE_UGL_FT_LUCIDA_10
#undef INCLUDE_UGL_FT_LUCIDA_12
#undef INCLUDE_UGL_FT_LUCIDA_14
#undef INCLUDE_UGL_FT_LUCIDA_18
#undef INCLUDE_UGL_FT_LUCIDA_24
#undef INCLUDE_UGL_FT_LUCIDA_I_08
#undef INCLUDE_UGL_FT_LUCIDA_I_10
#undef INCLUDE_UGL_FT_LUCIDA_I_12
#undef INCLUDE_UGL_FT_LUCIDA_I_14
#undef INCLUDE_UGL_FT_LUCIDA_I_18
#undef INCLUDE_UGL_FT_LUCIDA_I_24
#undef INCLUDE_UGL_FT_LUCIDA_B_08
#undef INCLUDE_UGL_FT_LUCIDA_B_10
#undef INCLUDE_UGL_FT_LUCIDA_B_12
#undef INCLUDE_UGL_FT_LUCIDA_B_14
#undef INCLUDE_UGL_FT_LUCIDA_B_18
#undef INCLUDE_UGL_FT_LUCIDA_B_24
#undef INCLUDE_UGL_FT_LUCIDA_BI_08
#undef INCLUDE_UGL_FT_LUCIDA_BI_10
#undef INCLUDE_UGL_FT_LUCIDA_BI_12
#undef INCLUDE_UGL_FT_LUCIDA_BI_14
#undef INCLUDE_UGL_FT_LUCIDA_BI_18
#undef INCLUDE_UGL_FT_LUCIDA_BI_24
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_08
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_10
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_12
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_14
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_18
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_24
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_I_08
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_I_10
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_I_12
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_I_14
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_I_18
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_I_24
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_B_08
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_B_10
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_B_12
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_B_14
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_B_18
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_B_24
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_BI_08
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_BI_10
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_BI_12
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_BI_14
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_BI_18
#undef INCLUDE_UGL_FT_LUCIDABRIGHT_BI_24
#undef INCLUDE_HTML
#undef INCLUDE_HTML_SSL
#undef INCLUDE_ENAVIGATOR
#undef INCLUDE_HTML_MAIL
#undef INCLUDE_HTMLWORKS
#undef INCLUDE_DOS_DISK


/*** PARAMETERS ***/

#undef  LOCAL_MEM_LOCAL_ADRS
#define LOCAL_MEM_LOCAL_ADRS (simMemBlock)
#undef  LOCAL_MEM_SIZE
#define LOCAL_MEM_SIZE (simMemSize)
#undef  LOCAL_MEM_AUTOSIZE
#undef  USER_RESERVED_MEM
#define USER_RESERVED_MEM 0
#undef  NV_RAM_SIZE
#define NV_RAM_SIZE NONE
#undef  NV_BOOT_OFFSET
#define NV_BOOT_OFFSET 0
#undef  VEC_BASE_ADRS
#define VEC_BASE_ADRS 0
#undef  EXC_MSG_OFFSET
#define EXC_MSG_OFFSET 0x800
#undef  EXC_MSG_ADRS
#define EXC_MSG_ADRS ((char *) (LOCAL_MEM_LOCAL_ADRS+EXC_MSG_OFFSET))
#undef  BOOT_LINE_SIZE
#define BOOT_LINE_SIZE 255
#undef  BOOT_LINE_ADRS
#define BOOT_LINE_ADRS sysBootLine
#undef  BOOT_LINE_OFFSET
#define BOOT_LINE_OFFSET 0x700
#undef  DEFAULT_BOOT_LINE
#define DEFAULT_BOOT_LINE sysBootLine
#undef  RESERVED
#define RESERVED 0
#undef  FREE_RAM_ADRS
#define FREE_RAM_ADRS simMemBlock
#undef  ROM_WARM_ADRS
#define ROM_WARM_ADRS (0x0)
#undef  STACK_SAVE
#define STACK_SAVE 0x40
#undef  USER_I_CACHE_MODE
#define USER_I_CACHE_MODE CACHE_WRITETHROUGH
#undef  USER_D_CACHE_MODE
#define USER_D_CACHE_MODE CACHE_WRITETHROUGH
#undef  USER_I_CACHE_ENABLE
#define USER_I_CACHE_ENABLE
#undef  USER_D_CACHE_ENABLE
#define USER_D_CACHE_ENABLE
#undef  SYS_CLK_RATE
#define SYS_CLK_RATE 60
#undef  SYS_CLK_RATE_MIN
#define SYS_CLK_RATE_MIN 19
#undef  SYS_CLK_RATE_MAX
#define SYS_CLK_RATE_MAX 1000
#undef  NUM_TTY
#define NUM_TTY 1
#undef  CONSOLE_TTY
#define CONSOLE_TTY 0
#undef  CONSOLE_BAUD_RATE
#define CONSOLE_BAUD_RATE 9600
#undef  NUM_FILES
#define NUM_FILES 50
#undef  CLEAR_BSS
#undef  WDB_STACK_SIZE
#define WDB_STACK_SIZE 0x2000
#undef  WDB_BP_MAX
#define WDB_BP_MAX 50
#undef  WDB_SPAWN_PRI
#define WDB_SPAWN_PRI 100
#undef  WDB_SPAWN_OPTS
#define WDB_SPAWN_OPTS VX_FP_TASK
#undef  WDB_TASK_PRIORITY
#define WDB_TASK_PRIORITY 3
#undef  WDB_TASK_OPTIONS
#define WDB_TASK_OPTIONS VX_UNBREAKABLE | VX_FP_TASK
#undef  WDB_RESTART_TIME
#define WDB_RESTART_TIME 10
#undef  WDB_MAX_RESTARTS
#define WDB_MAX_RESTARTS 5
#undef  INCLUDE_CONSTANT_RDY_Q
#define INCLUDE_CONSTANT_RDY_Q
#undef  ROOT_STACK_SIZE
#define ROOT_STACK_SIZE 20000
#undef  ISR_STACK_SIZE
#define ISR_STACK_SIZE 50000
#undef  INT_LOCK_LEVEL
#define INT_LOCK_LEVEL 0x1
#undef  ENV_VAR_USE_HOOKS
#define ENV_VAR_USE_HOOKS TRUE
#undef  NUM_DRIVERS
#define NUM_DRIVERS 20
#undef  MAX_LOG_MSGS
#define MAX_LOG_MSGS 50
#undef  WV_DEFAULT_BUF_MIN
#define WV_DEFAULT_BUF_MIN 4
#undef  WV_DEFAULT_BUF_MAX
#define WV_DEFAULT_BUF_MAX 10
#undef  WV_DEFAULT_BUF_SIZE
#define WV_DEFAULT_BUF_SIZE 0x8000
#undef  WV_DEFAULT_BUF_THRESH
#define WV_DEFAULT_BUF_THRESH 0x4000
#undef  WV_DEFAULT_BUF_OPTIONS
#define WV_DEFAULT_BUF_OPTIONS 0x0

#endif /* INCprjParamsh */
